### ISSUE TITLE
No hostapd-edimax.conf file

### ISSUE THREAD

**Issue by peepsnet** [jpoirier/stratux-setup#2]
https://github.com/jpoirier/stratux-setup/blob/9a7eccc4fc3923b2330a01b56681e947b3f70ca8/rpi.sh#L68-L95
your pi0/2 check does not contain the hostapd-edimax.conf file after fetching the binary... 

Are you relying on the Stratux make/make install to provide the file??

**Comment by jpoirier** [comment]
see https://github.com/jpoirier/stratux-setup/blob/9a7eccc4fc3923b2330a01b56681e947b3f70ca8/wifi-ap.sh#L71-L80

**Comment by peepsnet** [comment]
Ok. I was rebuilding my pi3 and since I use the edimax & onboard wifi your script didnt load all the edimax stuff. 

I wrote my own script for getting my rpi3 working. https://github.com/peepsnet/stratux/blob/master/image/stratuxPi3EdimaxFix.sh

I use the edimax so I can have a wlan0(stratux) and wlan1(connect to home wifi). If you remmeber https://github.com/cyoung/stratux/pull/377
