### ISSUE TITLE
PI zero fixup to stratux-setup

### ISSUE THREAD

**Issue by specialed1790** [jpoirier/stratux-setup#43]
add PI zero as a revision option 
RPI3BxREV=a02082
RPI3ByREV=a22082
RPIZEROW=9000c1  

add the following:
cd && git clone https://github.com/WiringPi/WiringPi.git && cd WiringPi/wiringPi && make static && make install-static

then add the LDFLAGS to build stratux from latest
[stratux-setup.sh.txt](https://github.com/jpoirier/stratux-setup/files/2130945/stratux-setup.sh.txt)

export CGO_LDFLAGS=-L/usr/local/lib

**Comment by jpoirier** [comment]
Sorry but this project is dead due to being out of sync with the stratux project and hasn't been updated for over a year.
